# Generated by Django 4.1.5 on 2026-03-26 23:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps_sth", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stage",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelTable(
            name="stage",
            table="sth_stage",
        ),
    ]
