services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: zeppelin
    ports:
      - "8000:8000"
      - "5555:5555"
    volumes:
      - ./backend:/app
      - ./.env:/app/.env
    working_dir: /app
    depends_on:
      - db_zeppelin
      - redis
    env_file:
      - .env
    command: supervisord -c /etc/supervisord.conf

  db_zeppelin:
    image: postgres:15
    container_name: db_zeppelin
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      #- ./create_tables.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
  redis:
    image: redis:7
    container_name: redis_zeppelin
    ports:
      - "6379:6379"
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: zeppelin_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - app

volumes:
  postgres_data:
