# Generated by Django 4.1.5 on 2026-03-26 23:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps_employee", "0003_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="sthstageexperiencelevel",
            table="sth_stage_experience_level",
        ),
    ]
