# Generated by Django 4.1.5 on 2026-03-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_questionnaire", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="comment_answer",
            field=models.TextField(blank=True, null=True),
        ),
    ]
