# Generated by Django 4.1.5 on 2026-03-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_questionnaire", "0003_alter_answer_comment_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionnaire",
            name="document",
            field=models.FileField(
                blank=True, null=True, upload_to="documents/%Y/%m/%d/"
            ),
        ),
    ]
