# Generated by Django 4.1.5 on 2026-03-26 22:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps_questionnaire", "0005_questionnaire_organization_questionnaire"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questionnaire",
            name="organization_questionnaire",
        ),
    ]
