# Generated by Django 4.1.5 on 2026-03-26 23:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps_questionnaire", "0006_remove_questionnaire_organization_questionnaire"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="adoptedlevel",
            table="adopted_level",
        ),
        migrations.AlterModelTable(
            name="answer",
            table="answer",
        ),
        migrations.AlterModelTable(
            name="questionnaire",
            table="questionnaire",
        ),
        migrations.AlterModelTable(
            name="statement",
            table="statement",
        ),
    ]
