# Generated by Django 4.1.5 on 2026-03-26 23:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps_organization", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="region",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="state",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelTable(
            name="organization",
            table="organization",
        ),
        migrations.AlterModelTable(
            name="organizationcategory",
            table="organization_category",
        ),
        migrations.AlterModelTable(
            name="organizationtype",
            table="organization_type",
        ),
        migrations.AlterModelTable(
            name="size",
            table="size",
        ),
        migrations.AlterModelTable(
            name="state",
            table="location",
        ),
    ]
