# Generated by Django 4.1.5 on 2026-03-26 23:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps_practitionerseye", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="element",
            options={"ordering": ["dimension__name", "name"]},
        ),
        migrations.AlterModelTable(
            name="category",
            table="practitioners_eye_category",
        ),
        migrations.AlterModelTable(
            name="element",
            table="practitioners_eye_element",
        ),
    ]
