# Generated by Django 4.1.5 on 2026-03-04 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_employee', '0001_initial'),
        ('apps_organization', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='organization_team',
            field=models.ForeignKey(help_text='organization', on_delete=django.db.models.deletion.CASCADE, to='apps_organization.organization'),
        ),
        migrations.AddField(
            model_name='team',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='team',
            name='responsible',
            field=models.ForeignKey(help_text='Employee', on_delete=django.db.models.deletion.CASCADE, to='apps_employee.employee'),
        ),
        migrations.AddField(
            model_name='sthstageknwoledgelevel',
            name='Knwoledge_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knwoledge_level_%(class)s', to='apps_employee.knwoledgelevel'),
        ),
        migrations.AddField(
            model_name='sthstageknwoledgelevel',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_%(class)s', to='apps_employee.employee'),
        ),
        migrations.AddField(
            model_name='sthstageknwoledgelevel',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
    ]
