# Generated by Django 4.1.5 on 2026-03-04 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_organization', '0001_initial'),
        ('apps_employee', '0002_initial'),
        ('apps_sth', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sthstageknwoledgelevel',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_%(class)s', to='apps_sth.stage'),
        ),
        migrations.AddField(
            model_name='sthstageexperiencelevel',
            name='employee_experience_level',
            field=models.ForeignKey(help_text="employee's knowledge", on_delete=django.db.models.deletion.CASCADE, related_name='employee_experience_level', to='apps_employee.employee'),
        ),
        migrations.AddField(
            model_name='sthstageexperiencelevel',
            name='experience_level',
            field=models.ForeignKey(help_text="employee's knowledge", on_delete=django.db.models.deletion.CASCADE, to='apps_employee.experiencelevel'),
        ),
        migrations.AddField(
            model_name='sthstageexperiencelevel',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='sthstageexperiencelevel',
            name='stage_experience_level',
            field=models.ForeignKey(help_text="employee's knowledge", on_delete=django.db.models.deletion.CASCADE, to='apps_sth.stage'),
        ),
        migrations.AddField(
            model_name='position',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='knwoledgelevel',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='experiencelevel',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='employeeknowledge',
            name='academic_degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic_degree_%(class)s', to='apps_employee.academicdegree'),
        ),
        migrations.AddField(
            model_name='employeeknowledge',
            name='academic_degree_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic_degree_status_%(class)s', to='apps_employee.academicdegreestatus'),
        ),
        migrations.AddField(
            model_name='employeeknowledge',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_%(class)s', to='apps_employee.employee'),
        ),
        migrations.AddField(
            model_name='employeeknowledge',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_organization_%(class)s', to='apps_organization.organization'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_%(class)s', to='apps_employee.position'),
        ),
        migrations.AddField(
            model_name='employee',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='academicdegreestatus',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='academicdegreecategory',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='academicdegree',
            name='academic_degree_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic_degree_category_%(class)s', to='apps_employee.academicdegreecategory'),
        ),
        migrations.AddField(
            model_name='academicdegree',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
    ]
